### ISSUE TITLE
Comparison with others

### ISSUE THREAD

**Issue by Carrotsniper** [aikunyi/FreTS#2]
Thanks for your amazing work.

For the "Long-term Time Series Forecasting" experiments shown in Table.2, I am confused about how these results were obtained.
For the ETTm1 dataset with a 96-96 setup:

| Model (Original Paper)   | ETTm1 MAE |
| --------   | ------- |
| LTSF-Linear   | 0.343    |
| PatchTST | 0.342     |

But in this paper, the results on ETTm1 changed as:
| Model   | ETTm1 MAE |
| --------   | ------- |
| FreTS   | 0.052    |
| LTSF-Linear  | 0.055     |
| PatchTST | 0.055     |

Could you please clarify my, Thanks!

**Comment by aikunyi** [comment]
we normalize them with the min-max normalization.
